# Generated by Django 4.2.16 on 2026-04-09 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0001_initial'),
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='id_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_nodo_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_inicio', to='nodos.nodo'),
        ),
        migrations.AddField(
            model_name='historia',
            name='id_portada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_portada', to='recursos.imagen'),
        ),
    ]
