# Generated by Django 4.2.16 on 2026-04-15 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dato', models.CharField(max_length=100)),
                ('tipo_movimiento', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar')], max_length=10)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('host_origen', models.CharField(blank=True, max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento en Bitácora',
                'verbose_name_plural': 'Bitácora de Movimientos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
