# Generated by Django 4.2.16 on 2026-04-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miusuario',
            name='activo',
        ),
    ]
