# Generated by Django 4.2.16 on 2026-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_miusuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='miusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
