# Generated by Django 4.2.16 on 2026-04-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0001_initial'),
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='historias.historia')),
                ('id_nodo_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='nodos.nodo')),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
            },
        ),
    ]
