# Generated by Django 4.2.16 on 2026-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Visitas',
                'verbose_name_plural': 'Contador de Visitas',
            },
        ),
    ]
